import sublime
import sublime_plugin
sublime.log_commands(True)

titles_all = [
    "Tyrian Explorer",
    "Tyrian Pathfinder",
    "Tyrian Trailblazer",
    "Tyrian Cartographer",
    "Canthan Explorer",
    "Canthan Pathfinder",
    "Canthan Trailblazer",
    "Canthan Cartographer",
    "Elonian Explorer",
    "Elonian Pathfinder",
    "Elonian Trailblazer",
    "Elonian Cartographer",
    "Tyrian Master Cartographer",
    "Canthan Master Cartographer",
    "Elonian Master Cartographer",
    "Tyrian Grandmaster Cartographer",
    "Canthan Grandmaster Cartographer",
    "Elonian Grandmaster Cartographer",
    "Legendary Cartographer",
    "Drunkard",
    "Incorrigible Ale-Hound",
    "Guardian of Tyria",
    "Guardian of Cantha",
    "Guardian of Elona",
    "Legendary Guardian",
    "Kind Of A Big Deal",
    "People Know Me",
    "I'm Very Important",
    "I Have Many Leather-Bound Books",
    "My Guild Hall Smells of Rich Mahogany",
    "God Walking Amongst Mere Mortals",
    "Party Animal",
    "Life of the Party",
    "Protector of Tyria",
    "Protector of Cantha",
    "Protector of Elona",
    "Tyrian Elite Skill Hunter",
    "Canthan Elite Skill Hunter",
    "Elonian Elite Skill Hunter",
    "Legendary Skill Hunter",
    "Survivor",
    "Indomitable Survivor",
    "Legendary Survivor",
    "Sweet Tooth",
    "Connoisseur of Confectionaries",
    "Tyrian Vanquisher",
    "Canthan Vanquisher",
    "Elonian Vanquisher",
    "Legendary Vanquisher",
    "Legendary Defender of Ascalon",
    "Lightbringer",
    "Adept Lightbringer",
    "Brave Lightbringer",
    "Mighty Lightbringer",
    "Conquering Lightbringer",
    "Vanquishing Lightbringer",
    "Revered Lightbringer",
    "Holy Lightbringer",
    "Sunspear Sergeant",
    "Sunspear Master Sergeant",
    "Second Spear",
    "First Spear",
    "Sunspear Captain",
    "Sunspear Commander",
    "Sunspear General",
    "Sunspear Castellan",
    "Spearmarshal",
    "Legendary Spearmarshal",
    "Not Too Smelly",
    "Not Too Dopey",
    "Not Too Clumsy",
    "Not Too Boring",
    "Not Too Annoying",
    "Not Too Grumpy",
    "Not Too Silly",
    "Not Too Lazy",
    "Not Too Foolish",
    "Not Too Shabby",
    "Delver",
    "Stout Delver",
    "Gutsy Delver",
    "Risky Delver",
    "Bold Delver",
    "Daring Delver",
    "Adventurous Delver",
    "Courageous Delver",
    "Epic Delver",
    "Legendary Delver",
    "Agent",
    "Covert Agent",
    "Stealth Agent",
    "Mysterious Agent",
    "Shadow Agent",
    "Underground Agent",
    "Special Agent",
    "Valued Agent",
    "Superior Agent",
    "Secret Agent",
    "Adventurer of the North",
    "Pioneer of the North",
    "Veteran of the North",
    "Conqueror of the North",
    "Master of the North",
    "Legendary Master of the North",
    "Slayer of Imps",
    "Slayer of Beasts",
    "Slayer of Nightmares",
    "Slayer of Giants",
    "Slayer of Wurms",
    "Slayer of Demons",
    "Slayer of Heroes",
    "Slayer of Champions",
    "Slayer of Hordes",
    "Slayer of All",
    "Tyrian Explorer",
    "Tyrian Pathfinder",
    "Tyrian Trailblazer",
    "Tyrian Cartographer",
    "Tyrian Master Cartographer",
    "Tyrian Grandmaster Cartographer",
    "Canthan Explorer",
    "Canthan Pathfinder",
    "Canthan Trailblazer",
    "Canthan Cartographer",
    "Canthan Master Cartographer",
    "Canthan Grandmaster Cartographer",
    "Elonian Explorer",
    "Elonian Pathfinder",
    "Elonian Trailblazer",
    "Elonian Cartographer",
    "Elonian Master Cartographer",
    "Elonian Grandmaster Cartographer",
    "Guardian of Tyria",
    "Guardian of Cantha",
    "Guardian of Elona",
    "Legendary Guardian",
    "Tyrian Elite Skill Hunter",
    "Canthan Elite Skill Hunter",
    "Elonian Elite Skill Hunter",
    "Legendary Skill Hunter",
    "Tyrian Vanquisher",
    "Canthan Vanquisher",
    "Elonian Vanquisher",
    "Legendary Vanquisher",
    "Champion",
    "Fierce Champion",
    "Mighty Champion",
    "Deadly Champion",
    "Terrifying Champion",
    "Conquering Champion",
    "Subjugating Champion",
    "Vanquishing Champion",
    "King's Champion",
    "Emperor's Champion",
    "Balthazar's Champion",
    "Legendary Champion",
    "Codex Initiate",
    "Codex Acolyte",
    "Codex Disciple",
    "Codex Zealot",
    "Codex Stalwart",
    "Codex Adept",
    "Codex Exemplar",
    "Codex Prodigy",
    "Codex Champion",
    "Codex Paragon",
    "Codex Master",
    "Codex Grandmaster",
    "Skillz",
    "Pro Skillz",
    "Numchuck Skillz",
    "Mad Skillz",
    "Über Micro Skillz",
    "Gosu Skillz",
    "1337 Skillz",
    "iddqd Skillz",
    "T3h Haxz0rz Skillz",
    "Pure Pwnage Skillz",
    "These skillz go to",
    "Real Ultimate Power Skillz",
    "Gladiator",
    "Fierce Gladiator",
    "Mighty Gladiator",
    "Deadly Gladiator",
    "Terrifying Gladiator",
    "Conquering Gladiator",
    "Subjugating Gladiator",
    "Vanquishing Gladiator",
    "King's Gladiator",
    "Emperor's Gladiator",
    "Balthazar's Gladiator",
    "Legendary Gladiator",
    "Hero",
    "Fierce Hero",
    "Mighty Hero",
    "Deadly Hero",
    "Terrifying Hero",
    "Conquering Hero",
    "Subjugating Hero",
    "Vanquishing Hero",
    "Renowned Hero",
    "Illustrious Hero",
    "Eminent Hero",
    "King's Hero",
    "Emperor's Hero",
    "Balthazar's Hero",
    "Legendary Hero",
    "Charmed",
    "Lucky",
    "Favored",
    "Prosperous",
    "Golden",
    "Blessed by Fate",
    "Hapless",
    "Unlucky",
    "Unfavored",
    "Tragic",
    "Wretched",
    "Jinxed",
    "Cursed by Fate",
    "Treasure Hunter",
    "Adept Treasure Hunter",
    "Advanced Treasure Hunter",
    "Expert Treasure Hunter",
    "Elite Treasure Hunter",
    "Master Treasure Hunter",
    "Grandmaster Treasure Hunter",
    "Seeker of Wisdom",
    "Collector of Wisdom",
    "Devotee of Wisdom",
    "Devourer of Wisdom",
    "Font of Wisdom",
    "Oracle of Wisdom",
    "Source of Wisdom",
    "Zaishen Supporter",
    "Friend of the Zaishen",
    "Companion of the Zaishen",
    "Ally of the Zaishen",
    "Sentinel of the Zaishen",
    "Steward of the Zaishen",
    "Defender of the Zaishen",
    "Warden of the Zaishen",
    "Bastion of the Zaishen",
    "Champion of the Zaishen",
    "Hero of the Zaishen",
    "Legendary Hero of the Zaishen",
    "Luxon Supporter",
    "Friend of the Luxons",
    "Companion of the Luxons",
    "Ally of the Luxons",
    "Sentinel of the Luxons",
    "Steward of the Luxons",
    "Defender of the Luxons",
    "Warden of the Luxons",
    "Bastion of the Luxons",
    "Champion of the Luxons",
    "Hero of the Luxons",
    "Savior of the Luxons",
    "Kurzick Supporter",
    "Friend of the Kurzicks",
    "Companion of the Kurzicks",
    "Ally of the Kurzicks",
    "Sentinel of the Kurzicks",
    "Steward of the Kurzicks",
    "Defender of the Kurzicks",
    "Warden of the Kurzicks",
    "Bastion of the Kurzicks",
    "Champion of the Kurzicks",
    "Hero of the Kurzicks",
    "Savior of the Kurzicks",
    "Commander",
    "Victorious Commander",
    "Triumphant Commander",
    "Keen Commande",
    "Battle Commander",
    "Field Commander",
    "Lieutenant Commander",
    "Wing Commander",
    "Cobra Commander",
    "Supreme Commander",
    "Master And Commander",
    "Legendary Commander",
]

titles = [
    "Not Too Smelly",
    "Not Too Dopey",
    "Not Too Clumsy",
    "Not Too Boring",
    "Not Too Annoying",
    "Not Too Grumpy",
    "Not Too Silly",
    "Not Too Lazy",
    "Not Too Foolish",
    "Not Too Shabby",
    "Guardian of Tyria",
    "Guardian of Cantha",
    "Guardian of Elona",
    "Hero",
    "Fierce Hero",
    "Mighty Hero",
    "Deadly Hero",
    "Terrifying Hero",
    "Conquering Hero",
    "Subjugating Hero",
    "Vanquishing Hero",
    "Renowned Hero",
    "Illustrious Hero",
    "Eminent Hero",
    "King's Hero",
    "Emperor's Hero",
    "Balthazar's Hero",
    "Legendary Hero",
    "Skillz",   
    "Pro Skillz",
    "Numchuck Skillz",
    "Mad Skillz",
    "Über Micro Skillz",
    "Gosu Skillz",
    "1337 Skillz",
    "iddqd Skillz",
    "T3h Haxz0rz Skillz",
    "Pure Pwnage Skillz",
    "These skillz go to",
    "Real Ultimate Power Skillz",
    "Survivor",
    "Indomitable Survivor",
    "Legendary Survivor",
    "Sweet Tooth",
    "Connoisseur of Confectionaries",
    "Charmed",
    "Lucky",
    "Favored",
    "Prosperous",
    "Golden",
    "Blessed by Fate",
    "Hapless",
    "Unlucky",
    "Unfavored",
    "Tragic",
    "Wretched",
    "Jinxed",
    "Cursed by Fate"
]


class ScriptTmpFileCommand(sublime_plugin.TextCommand):

    def script_tmp_file(self):
        # import random
        # title = random.choice(titles)
        # title = title.lower().replace(" ", "-")
        # tmp_file = "/tmp/" + title + ".txt"

        import uuid
        tmp_file = "/tmp/" + str(uuid.uuid4())

        open(tmp_file, 'a+').close()
        w = sublime.active_window()
        w.open_file(tmp_file)
        pass

    def run(self, edit):
        self.script_tmp_file()