alias l='ls -lFh --color=auto --group-directories-first'
alias ls='ls --color=auto --group-directories-first'
alias lt='ls -lhrt --color=auto --group-directories-first'
alias ldot='ls -ld .*'
alias grep='grep --color=auto'
alias mocp='mocp -T rhowaldt'
alias clip='xclip -selection clipboard'
alias edit='cat > /tmp/_.txt; subl /tmp/_.txt'
alias cat='bat --style=plain'
alias tmuxw='$HOME/dotfiles/tmux/tmux.startup.shell'
alias tmuxh='$HOME/dotfiles/tmux/tmux.startup.home'